// ZIP export uses stored entries; no library, server or external dependency.
((root,factory)=>{
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;else root.EvaOrSiteExport=api;
})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  const encoder=new TextEncoder();
  function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
  function zip(files){
    const chunks=[],central=[];let offset=0;
    for(const [name,content] of files){
      const filename=encoder.encode(name),bytes=typeof content==='string'?encoder.encode(content):content,crc=crc32(bytes);
      const header=new Uint8Array(30+filename.length),v=new DataView(header.buffer);
      v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,0x21,true);
      v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,filename.length,true);header.set(filename,30);
      chunks.push(header,bytes);
      const entry=new Uint8Array(46+filename.length),e=new DataView(entry.buffer);
      e.setUint32(0,0x02014b50,true);e.setUint16(4,20,true);e.setUint16(6,20,true);e.setUint16(8,0x800,true);e.setUint16(14,0x21,true);
      e.setUint32(16,crc,true);e.setUint32(20,bytes.length,true);e.setUint32(24,bytes.length,true);e.setUint16(28,filename.length,true);e.setUint32(42,offset,true);entry.set(filename,46);
      central.push(entry);offset+=header.length+bytes.length;
    }
    const end=new Uint8Array(22),e=new DataView(end.buffer),size=central.reduce((n,a)=>n+a.length,0);
    e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);
    return new Blob([...chunks,...central,end],{type:'application/zip'});
  }
  function bundle(config,math,renderer,runtime,fontBase64){
    // A private namespace keeps the host site's globals and editor code isolated.
    return `/* EvaOr website logo — generated by EvaOr Studio */\n(()=>{\nconst globalThis={};const module=undefined;\n${math}\n${renderer}\nconst {EvaOrParticles,EvaOrRenderer}=globalThis;\nconst EVAOR_CONFIG=${JSON.stringify(config)};\nconst EVAOR_FONT=${JSON.stringify(fontBase64)};\n${runtime}\n})();\n`;
  }
  function demo(config){
    const background=config.settings.background;
    return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>EvaOr — логотип для сайта</title>
<style>body{margin:0;background:${background};color:${config.textColor};font:16px system-ui,sans-serif}header{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:20px 5%;border-bottom:1px solid #8885}evaor-logo{width:260px;max-width:60vw}button{padding:12px 18px;border:1px solid #888;border-radius:24px;color:inherit;background:transparent}main{max-width:700px;padding:64px 5%;line-height:1.7}code{word-break:break-word}@media(max-width:480px){header{gap:12px}evaor-logo{width:190px}button{font-size:12px}}</style>
<script src="evaor-logo.js" defer></script></head><body>
<header><evaor-logo href="./demo.html" aria-label="EvaOr — главная"></evaor-logo><button id="order">Начать проект</button></header>
<main><h1>Ваш логотип в хедере</h1><p>Сохранённая форма света, цвета, скорость, Montserrat и композиция. Наведите на логотип или кнопку, чтобы увидеть реакцию.</p><p>Анимация работает на прозрачном фоне. Цвет страницы можно изменить в CSS. Инструкция по установке находится в файле README.txt.</p></main>
<script>const logo=document.querySelector('evaor-logo'),button=document.querySelector('#order');for(const event of ['pointerenter','focus'])button.addEventListener(event,()=>logo.setIntensity(1));for(const event of ['pointerleave','blur'])button.addEventListener(event,()=>logo.setIntensity(0));</script>
</body></html>`;
  }
  const snippet=`<!-- Добавьте скрипт один раз: путь должен вести к загруженному файлу -->
<script src="/assets/evaor/evaor-logo.js" defer></script>

<!-- Поместите логотип внутри хедера -->
<evaor-logo href="/" aria-label="EvaOr — главная" style="width:240px;max-width:100%;"></evaor-logo>
`;
  const guide=`EvaOr — логотип для сайта

1. Распакуйте архив. Откройте demo.html, чтобы посмотреть выбранный логотип в хедере.
2. Загрузите evaor-logo.js на ваш сайт, например в /assets/evaor/.
3. Вставьте код из embed.html в страницу. Укажите фактический путь к скрипту. Скрипт подключается один раз; элемент evaor-logo размещается в хедере.
4. Атрибут href задаёт переход на главную. Ширина задаётся в CSS; высота рассчитывается автоматически. Например: evaor-logo { width: 240px; max-width: 100%; }.

Цвет текста уже выбран под фон студии. Для другого фона задайте text-color="#ffffff" или text-color="#101014" на элементе. Частицы и текст рисуются на прозрачном фоне; цвета анимации сохранены в пакете. O, шрифт и интервалы соответствуют настройкам студии.

Наведение и клавиатурный фокус усиливают анимацию. interactive="false" отключает реакцию логотипа. Чтобы связать логотип с другой кнопкой, используйте logo.setIntensity(1) при наведении и logo.setIntensity(0) при уходе, где logo = document.querySelector('evaor-logo'). Пример есть в demo.html.

logo.pause() и logo.play() останавливают и запускают анимацию. Атрибут paused также останавливает её. Экспорт начинает анимацию с сохранённой фазы независимо от паузы в редакторе; скорость 0 даёт статичный вариант. При системной настройке уменьшения движения показывается неподвижный кадр. За пределами экрана и в скрытой вкладке движение приостанавливается.

В пакете нет панели настроек и зависимости от студии. Шрифт Montserrat встроен в JS, внешние сервисы и запросы не нужны. Код работает в современных Chrome, Edge, Safari и Firefox с поддержкой Canvas и Web Components. Строгая политика CSP должна разрешать используемые Canvas, встроенный стиль компонента и font-src data:. Если платформа запрещает скрипты в контенте, подключите файл через шаблон сайта или попросите разработчика.

WordPress: подключите JS в теме/дочерней теме и разместите элемент в шаблоне хедера. React/Next.js: подключите JS на стороне браузера один раз, затем используйте элемент evaor-logo (при TypeScript добавьте описание custom element). Настройки сохранены в evaor-preset.json для повторного открытия в студии.

Несколько элементов на одной странице используют один экспортированный вариант. Для смены варианта повторите экспорт и замените JS. Одновременно подключайте только один evaor-logo.js.

Montserrat распространяется по SIL Open Font License. Сохраните OFL-Montserrat.txt при передаче пакета.
`;
  async function create(snapshot){
    const background=snapshot.settings.background.slice(1).match(/../g).map(v=>parseInt(v,16));
    const config={...snapshot,composition:{...snapshot.composition,view:'logo'},textColor:background[0]*.2126+background[1]*.7152+background[2]*.0722>160?'#101014':'#fcfcfc'};
    const assetURL=name=>{const script=Array.from(document.scripts).find(s=>new URL(s.src||document.baseURI).pathname.endsWith('/'+name));return script?.src||new URL(name,document.baseURI).href;};
    const names=['particle-math.js','logo-renderer.js','logo-embed.js','fonts/Montserrat-Variable.ttf','fonts/OFL-Montserrat.txt'];
    const results=await Promise.all(names.map(async name=>{const response=await fetch(assetURL(name),{cache:'no-cache'});if(!response.ok)throw new Error('Не удалось загрузить '+name);return new Uint8Array(await response.arrayBuffer());}));
    const decoder=new TextDecoder();let font='';for(let i=0;i<results[3].length;i+=8192)font+=String.fromCharCode(...results[3].subarray(i,i+8192));
    const js=bundle(config,...[results[0],results[1],results[2]].map(bytes=>decoder.decode(bytes)),btoa(font));
    return zip([['evaor-logo.js',js],['demo.html',demo(config)],['embed.html',snippet],['README.txt',guide],['evaor-preset.json',JSON.stringify(config,null,2)],['OFL-Montserrat.txt',results[4]]]);
  }
  return {create,zip,bundle,demo,snippet,guide};
});
